spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EVRentalSystem;encrypt=false;trustServerCertificate=true
    username: sa
    password: 12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
server:
  port: 8084
  servlet:
    context-path: /EVRentalSystem


